= Jenkins Infra Datadog monitoring
:toc:

This repository is meant to hold configuration files of Jenkins infrastructure monitoring stuff.

This repository hosts the infrastructure-as-code definition for all the link:https://www.datadoghq.com/:[DataDog] monitoring resources for the link:https://www.jenkins.io/projects/infrastructure/[Jenkins Infrastructure Project].

== Requirements

* An access to the Jenkins Datadog account for the Jenkins Infrastructure at https://jenkins.datadoghq.com.
* The requirements (of the shared tools) listed at link:https://github.com/jenkins-infra/shared-tools/tree/main/terraform#requirements[shared-tools/terraform#requirements]
* The link:https://www.terraform.io/language/settings/backends/azurerm[Terraform AzureRM Backend Configuration] on a local file named `backend-config`:
** The content can be retrieved from the credentials of infra.ci.jenkins.io.
** This file (`backend-config`) is git-ignored

* The git command line to allow cloning the repository and its submodule link:https://github.com/jenkins-infra/shared-tools[shared-tools]
** This repository has submodules. Once you cloned the repository, execute the following command to obtain the shared tools:

[source,bash]
----
git submodule update --init --recursive
----

== Monitors

DataDog monitors are configured through link:https://www.terraform.io/[Terraform] with the link:https://www.terraform.io/docs/providers/datadog/index.html[datadog] provider.


Once you've fulfilled the <<Requirements>>, you may execute any command from https://github.com/jenkins-infra/shared-tools/blob/main/terraform/README.adoc#available-commands by adding the correct flag `--directory` pointing to `.shared-tools/terraform/`:

[source,bash]
----
make --directory=.shared-tools/terraform help
make --directory=.shared-tools/terraform lint
# ...
----

A usual change (add/update/remove a datadog monitor for instance) to this repository looks like the following:

* Fork the repository and clone it locally
* Follow the <<Requirements>> steps to obtain the shared tools
* Start by running a full `make --directory=.shared-tools/terraform validate` command to ensure that you work on a sane base (should generate a report TXT file with no changes to be applied)
* Edit the Terraform project files
* Run the command `make --directory=.shared-tools/terraform validate` again to ensure that your changes are OK
* Commit, push and open a pull request to let the Jenkins pipeline run the test + plan (as per https://github.com/jenkins-infra/shared-tools/blob/main/terraform/README.adoc#jenkins-pipeline)
